//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SklyarovaDemka
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int id { get; set; }
        public int id_guest { get; set; }
        public int id_rooms { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
